accounts/urls.py
from django.urls import path
from django.urls import reverse
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),

    path('password_reset/', PasswordResetView.as_view(
            template_name='accounts/reset_password.html',
            success_url='done/',
            email_template_name='accounts/reset_password_email.html'),
         name='password_reset'),

    path('password_reset/done/', PasswordResetDoneView.as_view(
            template_name='accounts/reset_password_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
            template_name='accounts/reset_password_confirm.html',
            success_url='/'),
         name='password_reset_confirm'),

    path('reset/done/', PasswordResetCompleteView.as_view(
            template_name='accounts/reset_password_complete.html'),
         name='password_reset_complete')
]

scripter/urls.py
from django.contrib import admin
from django.urls import path, include
from scripter import views

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.

class UserProfile(models.Model):
    # User test information (Not production fields)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])



post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)


    class Meta:
        model = User
        fields = ['username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2']

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']


        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):


    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password'
        ]
        #exclude = {}

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    numbers = [1,2,3,4,5] #Dummy data
    name = "Chris Villegas"

    args = {'myname':name,
            'numbers': numbers}
    return render(request, 'accounts/home.html', args)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('home'))
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('view_profile'))

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('view_profile'))
        else:
            return redirect(reverse('change_password'))
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

scripter/views.py
from django.shortcuts import redirect
from django.urls import reverse


def login_redirect(request):
    return redirect(reverse('login'))

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<h1>HOME</h1>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        You can log in here
    </p>
    <h2>Login </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Logged Out</h1>
    <p>
        You have logged out
    </p>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="container">
    <h1>Profile Information</h1>
    <p>username: {{ user }}</p>
    <p>first name: {{ user.first_name}}</p>
    <p>last name: {{ user.last_name }}</p>
    <p>email: {{ user.email }}</p>
</div>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password Reset </h1>
    <p>
        Forgotten your password? Enter your email address below,
        and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password Reset Complete</h1>
    <p>
        You have successfully changed your password.
    </p>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Enter a new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password Reset Sent</h1>
    <p>
        We sent an email for resetting your password
    </p>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

	{% trans "Thanks for using our site!" %}

	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

	{% endautoescape %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
              crossorigin="anonymous">
        {% block head %}
        <title></title>
        {% endblock %}
    </head>
    <body>
        <br>
        <!-- Navigation Bar -->
        <div class="container">
          <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
            <a class="navbar-brand" href="/">Scripter</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExample09">

              {% if user.is_authenticated %}

              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:logout' %}">Logout<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:view_profile' %}">Profile</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:change_password' %}">Change Password</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:password_reset' %}">Reset Password</a>
                </li>
              </ul>
              <form class="form-inline my-2 my-md-0">
                <input class="form-control" type="text" placeholder="Search" aria-label="Search">
              </form>

              {% else %}

              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
                </li>
              </ul>
              <form class="form-inline my-2 my-md-0">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                  </li>
                </ul>
              </form>

              {% endif  %}

            </div>
          </nav>
        </div>

        {% block body %}
        {% endblock %}
    </body>
</html>